Create R Script for Sorting Vignettes from Trello List
Bioconductor/sweave2rmd pull request #54
Opened 2023-01-24 14:25 UTC by BerylKanali

@jwokaty 
Tried to put everything that is working currently here and I will update as we improve the script. It's more of hardcoded. If you have any reviews or suggestions let me know.

Milestones:
- We can import data and retrieve package names and get their specific ranks then display the package name and rank.
- Packages displayed are from version 3.17

Obstacles:
- Getting individual maintainer for each package, the function is set to get all of the packages of a certain maintainer at once.(Still researching on it)
- At some point the code displaying individual ranks breaks, trying to figure it out.

To do:
- Create a function that sorts the packages according to rank and then assigns them a category(high or low depending on a certain threshold)
- Display all these in a excel file which will be the final output file.

2023-01-25 05:23 UTC, jwokaty commented
@BerylKanali, I wanted to give some general feedback before we pair program so that you have time to think about the process.

We don't need to find each package's maintainer; we just need to know if they're maintained by the Bioconductor core team to categorize them as `To Do` or `Contact Maintainer` (a new label) on the Github Project Board. Look back at #49 and make sure you understand all parts.

Consider what might make good variables given that we'd like to reuse the script and that it might take time (several months or year) before we use it again on a similar file.

Try to think in terms of functions to separate functionality. It's a choice when you have a small script, but then you can break the problem into smaller, testable pieces with clear functionality. 

Try to choose variables whose names make it obvious what they contain and what their relation is to the surrounding code. You can imagine if you had a very large package with many variables or if you need to fix a package you wrote a year ago that you might forget the purpose of a variable. I would also avoid using keywords as variable or function names, such as `data`.

I would suggest using `<-` for assignment. `=` isn't wrong, but I think `<-` is preferred.

I can see how you experimented with the functions in BiocPkgTools, which is great.  I also appreciate your documentation to help me understand where you're going. I didn't see any attempts to use one of the `apply` functions as we previously discussed. I would also think about how you're going to preserve the later put the results in a file.

2023-01-26 19:26 UTC, jwokaty commented
I figured out what was wrong with my code. I think maybe I didn't initialize `version` after ran the loop.

The function I was looking for at the end of our session was `attributes`, which can tell you a little about an object's structure in the same way we were using `class`.

I haven't encountered the error you mentioned, so let's look at that tomorrow.

2023-01-26 19:32 UTC, BerylKanali commented
> I figured out what was wrong with my code. I think maybe I didn't initialize `version` after ran the loop.
> 
> The function I was looking for at the end of our session was `attributes`, which can tell you a little about an object's structure in the same way we were using `class`.
> 
> I haven't encountered the error you mentioned, so let's look at that tomorrow.

Great. We can try figuring it out tomorrow if I will not have solved it.

2023-02-07 15:24 UTC, BerylKanali commented
@jwokaty 
I have added the latest changes to the script.

2023-02-08 20:26 UTC, jwokaty requested changes
* Let's be consistent with our usage of `<-`, as well as spacing around it. Change assignments with equals such as line 9 to use `<-`.
* `version`  and `threshold` should be variables listed at the top. This is so that the user will know to change these specific variables to alter the script rather than looking for it in the body of the script. I would also make the file name a variable.
* Remove lines such as 6, 10, 19, etc., where you are testing the values of the variables.
* Line 14 should use the `version` variable.
* Remove line 15 as it may be a different repo in the future when we reuse the script. By default, the function will check all repositories, which is fine.
* Be consistent about spacing.
* Remove lines 32-33. These are the default values for `biocMaintained`, so you don't need to restate them. You can just do `maintainer <- biocMaintained()` or you could also combine it with line 39 for `coreMaintained <- list(biocMaintained()$Package)`
* Generally, all `library` calls should be at the top.
* Generally, we try to avoid doing `install.packages` via a script. It's better if the user does this separately so they can control what's installed on their computer. I would put both `BiocPkgTools` and `openxlsx` as a `Dependency` in the `DESCRIPTION`. I would check other packages to see how they do it, like https://github.com/Bioconductor/GenomicFeatures/blob/master/DESCRIPTION.
 * I would think a little more about what are appropriate names for functions. There are `packagenames`, `pckgs`, `pckgsnew`, and `pkgsList` when I read this, I don't necessarily know what's in them. I strongly suggest that you use descriptive names to make your script more readable and maintainable. In R, we also use camel case, so it's good to get in the habit of writing, for example, `packageNames` and `coreMaintained` for readability.
 * I also recommend writing an explanation of the script at the top that mentions the purpose, how to use it, what variables to set.

2023-02-10 21:04 UTC, BerylKanali commented
@jwokaty 
I made a commit earlier today with the suggested changes.

2023-02-10 23:15 UTC, jwokaty requested changes
- [ ] Add `BiocPkgTools` and `openxlsx` as dependencies in the DESCRIPTION file.
- [ ] Run your code and make sure it works. I seem some variation on variable names (`packageNames` != `packagenames` and `coreMaintained` != `coremaintained`).
- [ ] Be consistent with spacing. Spacing after commas, documentation next to code, before and after `(`. I know I am being very strict, but good habits will go a long way in making your code readable for the future. We will use this script again so please think of the developer who will come after you to use or modify it.

For the next step, think of how to accomplish the last part of this script, to document packages not in the devel version of Bioconductor. I'd like you to propose how it can be done and try to add it. Make sure your code works first. Commit it. Then work on this section.

2023-02-10 23:15 UTC, jwokaty commented on inst/script/Trello_Sort.R
> +filepath <- "https://trello.com/1/cards/61d9de5dffd84647db58edb7/attachments/61d9de7a6b634f8b08261871/download/rnw-files.txt"
I would move `filepath`  after output_file.

2023-02-10 23:15 UTC, jwokaty commented on inst/script/Trello_Sort.R
> +# creating a list of packages from the vignette list that are in version 3.17
I would remove the mentions of a specific version (3.17) from the documentation in lines 34 and 41. You could say `Get packages in specified Bioconductor version` and `Create list of packages from vignette list in specified version`.

2023-02-21 13:05 UTC, jwokaty requested changes
- [ ] Rename the script. I think we want to avoid calling the script 'trello' because Trello isn't actually involved at all in the process, except maybe the url, which may be a path to a file in the future. It would be better named 'categorize_vignettes.R' or something similar.
- [ ] For the README, document what the script does (it categorizes a list of packages in a given version of Bioconductor for a given repo with respect to a threshold value ...), what you need to run the script, which includes the inputs, and how to run the script. It should also describe the output.  Let's omit implementation details.
- [ ] Wrap long lines.
- [ ] Fix spelling errors.

2023-02-27 15:34 UTC, jwokaty requested changes

2023-02-27 15:34 UTC, jwokaty commented on README.md
> +-   **Version** : The Bioconductor version that will be used in the script.
I would keep these lowercase so it doesn't confuse anyone, so `threshold` and `version`.

2023-02-27 16:07 UTC, BerylKanali commented
Hi @jwokaty 
I have remove implementation details, fixed spelling and wrapped long lines. I have also made some changes in the README details.

2023-02-27 18:40 UTC, jwokaty requested changes
Please reread your documentation for spelling, clarity, and formatting errors.

2023-02-27 18:40 UTC, jwokaty commented on README.md
> +filepath declared earlier) to the script and run the script.
What we want here is instructions to run, such as `Rscript categorize_vignettes.R`. (Make sure this works!)

2023-02-27 18:40 UTC, jwokaty commented on README.md
> +40 is considered as a high priority package.
Can you add that the lower the number, the higher the priority because I think it isn't clear or intuitive.

2023-02-27 20:34 UTC, jwokaty commented on README.md
> +filepath declared earlier) to the script and run the script.
You should provide the exact command to run in the terminal for the user: `Rscript categorize_vignettes.R`.

2023-02-27 20:47 UTC, BerylKanali commented
@jwokaty I have gone through the script, made some changes then did a grammar and spell check on it please let me know if I have missed something.

Just realized in the code that this function `priority = ifelse(rank[[1]] > threshold, "High","Low")` should be 
`priority = ifelse(rank[[1]] < threshold, "High","Low")`. If I am not wrong.

Since the lower the rank number the higher priority the package. Eg S4Vectors

Also noticed a discrepancy maybe that is why we did not notice the error above:
The rank we get in our final excel is different from what we would get if we looked for the rank of a specific package:
Example: 

> > rank1 <- pkgDownloadRank("S4Vectors","software" ,version)
> rank1
2/2083 
   0.1 
But in our excel sheet, you can look at the one you share on slack which is

> S4Vectors 45.05 High

This does not seem mathematically correct. I don't understand why we  are getting 45.05.

We can discuss this. If we figure this out we will know if this statement is correct or should remain as it was initially.

> Just realized in the code that this function `priority = ifelse(rank[[1]] > threshold, "High","Low")` should be 
`priority = ifelse(rank[[1]] < threshold, "High","Low")`. If I am not wrong.

>

2023-02-28 15:58 UTC, jwokaty commented on inst/script/categorize_vignettes.R
> +                        Action = ifelse(i %in% pckgs, "Action needed", "Action not needed"))
Becareful here because `i` is an index and not the package name itself. So you should also modify lines 60 and 61 to get the package name. I would also set `Action` to be `action` in line 61.

2023-03-01 23:23 UTC, jwokaty requested changes
Please give everything a good look. Make sure the code is working.

2023-03-01 23:23 UTC, jwokaty commented on inst/script/categorize_vignettes.R
> +}}
Let's make pkgsList have the same columns: package, rank, priority, and status. When a package is not in the current version, set the status to 'deprecated' rather than 'action not needed' (this makes it clear that the package is no longer in Bioconductor) and set `rank = "", priority = ""` so that they are blank for that package.

Since we're removing the column `action` completely, please update the documentation to be consistent with the new output.

Please fix formatting of this section so that it's easier to read/maintain. The if/else statement and brackets should line up. The lines within the if and else sections should be indented.

2023-03-02 23:25 UTC, merged

2023-03-02 23:26 UTC, jwokaty commented
@BerylKanali Good work. I made a few changes to fix formatting, clarify the content of the input file and the implementation. You can see these changes at https://github.com/Bioconductor/sweave2rmd/pull/54/commits/5c29fcfeaac13c540357003418841356f60b83d2 for your reference. We'll be using this to find candidate vignettes for the  next round of Outreachy.