Update checklist
Bioconductor/sweave2rmd pull request #70
Opened 2023-04-10 19:04 UTC by sonali8434

@jwokaty  This is PR for this issue, I tried to solve every issue mentioned if any further changes are needed please let me know.
 Thank you

2023-04-10 19:09 UTC, sonali8434 commented
The checks are failed do I need to create a new PR?

2023-04-12 11:37 UTC, sonali8434 commented
The build website action failed I think same issue is there in #50 for which you have already created an issue #52 .

2023-04-12 19:21 UTC, jwokaty commented on vignettes/contribute.Rmd
> +  refer this [.Rmd](https://github.com/Bioconductor/genefilter/blob/devel/vignettes/howtogenefinder.Rmd)
Rather than referring to another vignette, it would be better to show examples directly of what is meant because there's a lot of room for interpretation.

2023-04-12 19:23 UTC, jwokaty commented on vignettes/contribute.Rmd
> +  refer to the contribution guide for acceptable formats
I think this is better decomposed into 2 parts. If you want to consolidate, maybe have 'If agreed upon ... ' at the beginning then 2 separate check boxes for YAML and the DESCRIPTION file.

2023-04-12 19:28 UTC, jwokaty commented on vignettes/contribute.Rmd
> +- [ ] Long lines have been broken up and reformatted.
It might be better to be explicit about how this is done using `Code > Reflow comment` in RStudio or describing or showing an example.

2023-04-12 19:29 UTC, jwokaty requested changes
Thanks for this pull request to improve our documentation. I made a few suggestions to improve clarity.

2023-04-12 19:30 UTC, jwokaty commented
> The build website action failed I think same issue is there in #50 for which you have already created an issue #52 .

It's okay to disregard the build action.

2023-04-13 07:50 UTC, sonali8434 commented
> Thanks for this pull request to improve our documentation. I made a few suggestions to improve clarity.

Thank you @jwokaty for your review I have some problems while documenting examples of code blocks (which I have shared in a [slack](https://community-bioc.slack.com/archives/C03E7TWE2NT/p1681358334081799) please resolve my issue at your free time, I have gone through the rest of review and understood the areas where I need to improve after resolving these issues completely I will commit my final changes later.. Till then I am currently working on improving the documentation.

2023-04-14 08:21 UTC, sonali8434 commented
@jwokaty  I have implemented the requested changes, and I would also like to discuss a few other matters. Firstly, can we modify the formatting of the checklist to match the example in the figure provided above? Additionally, in the contribute document, there is a section on pandoc that includes a note which states: "Note: We currently use this method to preprocess files since we can't directly convert from Sweave (.Rnw) to R Markdown (.Rmd). pandoc has some issues processing chunks of code, so we'll have to manually correct these sections of the .Rmd file." However, there is no explanation or examples provided on how to manually convert a code chunk. Would you like me to address this issue and make the necessary changes to provide clearer instructions and examples?

2023-04-18 16:47 UTC, sonali8434 commented
@jwokaty  I have implemented the requested changes, If any further modifications are required please let me know.


 I would also like to discuss a section, in the contribute document, there is a section on pandoc that includes a note which states: "Note: We currently use this method to preprocess files since we can't directly convert from Sweave (.Rnw) to R Markdown (.Rmd). pandoc has some issues processing chunks of code, so we'll have to manually correct these sections of the .Rmd file." However, there is no explanation or examples provided on how to manually convert a code chunk. Would you like me to address this issue and make the necessary changes to provide clearer instructions and examples?

2023-04-18 20:33 UTC, sonali8434 commented
I also want to ask can I include this PR in my contribution to outreachy final application? I have not included it till now since I am not sure.

here is the final updated checklist :

- [ ] the `.Rmd` file knits to `HTML`
- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [ ] the `.Rnw` file has been removed
- In the `DESCRIPTION` file :
  - [ ] `BiocStyle` and `knitr` are listed in `Suggests`
  - [ ] the line `VignetteBuilder: knitr` exists
  - [ ] any added lines use the same spacing and indents as the existing document
- If agreed with the Maintainer :
  - [ ] the contributor is in the author list in the `DESCRIPTION` file.
  - [ ] the contributor is in the author list in the vignette's YAML.
  - Refer to the contribution guide for acceptable formats
- If this pull request involves converting from separate `Author` and  `Maintainer`
  lines to the `Authors@R` vector, please ensure that :
  - [ ] the `Authors@R` vector includes the maintainer as specified with `role='cre'`.
  - [ ] the `Maintainer` line is completely removed.
- [ ] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [ ] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [ ] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`
- [ ] Only files necessary for the conversion are included in the pull request.
- [ ] Long lines have been broken up and reformatted, you can achieve this by
  selecting the text in your script and then clicking on `Code > Reflow Comment`
  in R Studio.
- [ ] Code blocks are surrounded by a blank line, and there are no blank lines
  before the start or after the end of the code within the code block.

2023-05-09 04:57 UTC, merged

2023-05-09 05:35 UTC, sonali8434 commented
Close #69