Update contribution doc to clarify manual edits after using pandoc code
Bioconductor/sweave2rmd pull request #73
Opened 2023-05-18 20:30 UTC by sonali8434

@jwokaty close #68

2023-06-02 20:16 UTC, jwokaty requested changes
These explanations are great. Thank you :)

2023-06-02 20:16 UTC, jwokaty commented on vignettes/contribute.Rmd
> +    sections of the .Rmd file you can refer the steps given in point no 14 for
Rather than referring to "point no 14", it might be better to make a link because we tend to edit a lot and the numbers can change. For example

```
sections of the .Rmd file. You can refer to [converting the code chunks manually](#converting_manually) below.
14. <a name="converting_manually">Steps for converting the code chunks manually</a>:
```

Note: I think we should use the same language to be clear and I also added Capitalization and punctuation.

2023-06-02 20:16 UTC, jwokaty commented on vignettes/contribute.Rmd
> +    and added Markdown formatting, you can knit the R Markdown vignette
Add `R` before `Markdown`

2023-06-02 20:16 UTC, jwokaty commented on vignettes/contribute.Rmd
> +    with the converted R Markdown vignette
Add a period

2023-06-03 09:23 UTC, sonali8434 commented on vignettes/contribute.Rmd
> +    with the converted R Markdown vignette
can you please explain a bit more? I did not understand what do you mean by adding period

2023-06-05 18:29 UTC, sonali8434 commented on vignettes/contribute.Rmd
> +    with the converted R Markdown vignette
You mean full stop hehe :). Ok I will made the required changes asap.

2023-06-06 04:45 UTC, sonali8434 commented
@jwokaty Made all the changes as requested.

2023-06-07 14:07 UTC, merged