Update Script code to add column for maintainers email
Bioconductor/sweave2rmd pull request #81
Opened 2023-06-09 10:13 UTC by sonali8434

Close #77  I have Updated a code bit to add one more column for maintainers name and email and also try to reduced some of the execution time of code @jwokaty Please Review.

2023-06-09 10:49 UTC, sonali8434 commented
I think we can also remove

```
pckgs<- c()
for (i in packageNames) {
  if (i %in% biocPckgs$Package)
    pckgs <- append(pckgs, i)
}
```
Since I have'nt use it anywhere just need you confirmation before removing this? I think this is the reason why the execution time is more although I am not sure about this.

2023-06-13 15:08 UTC, jwokaty requested changes
@sonali8434 Thanks for this PR. Could I ask you to make these two changes before I merge the PR?

2023-06-13 15:08 UTC, jwokaty commented on inst/script/categorize_vignettes.R
>  # Create list of packages from vignette list in specified version
I think lines 38-44 can be removed.

2023-06-13 17:11 UTC, sonali8434 commented on inst/script/categorize_vignettes.R
>  # Create list of packages from vignette list in specified version
Done.

2023-06-13 18:31 UTC, merged