update troubleshooting-faq
Bioconductor/sweave2rmd pull request #87
Opened 2023-06-28 18:07 UTC by sonali8434

Close #86  @jwokaty Please review this PR I was planning to link this question in the contribute document.

2023-06-28 18:50 UTC, jwokaty requested changes
It might be good to share an example of what this might look like.

2023-06-28 18:50 UTC, jwokaty commented on vignettes/troubleshooting-faq.Rmd
> +### *Question:* How can one handle the `end of document` error when using tools like pandoc or RnwtoRmd?
Change `RnwtoRmd` to `Rnw2Rmd`.

2023-06-28 18:50 UTC, jwokaty commented on vignettes/troubleshooting-faq.Rmd
> +his error prevents the successful execution of the code, leading to the failure in
Change `his error` to `This error`

2023-06-29 13:01 UTC, sonali8434 commented on vignettes/troubleshooting-faq.Rmd
> +### *Question:* How can one handle the `end of document` error when using tools like pandoc or RnwtoRmd?
Done

2023-06-29 13:01 UTC, sonali8434 commented on vignettes/troubleshooting-faq.Rmd
> +his error prevents the successful execution of the code, leading to the failure in
Done

2023-06-29 13:44 UTC, jwokaty requested changes
I think we'll be ready after this change.

2023-06-29 13:44 UTC, jwokaty commented on vignettes/troubleshooting-faq.Rmd
> +this error prevents the successful execution of the code, leading to the failure
It might be better to be clear that it is when running pandoc or Rnw2Rmd can generate the error and the failure is the error message and that the .Rmd doesn't get created.

    *Background information:* During the conversion process while running `pandoc` or `Rnw2Rmd`,  
    an "unexpected end of document" error prevents the .Rmd file from being created. For example,
    the error message states:
    ```
    Error at "C:/Users/path.Rnw" (line 554,column 2):
    unexpected end of document
    ^
    ```

2023-06-29 17:04 UTC, jwokaty approved these changes

2023-06-29 17:05 UTC, merged