add Rnw2Rmd as a process for conversion
Bioconductor/sweave2rmd pull request #89
Opened 2023-08-07 17:12 UTC by sonali8434

2023-08-07 17:15 UTC, sonali8434 commented
close #83  and close #82

2023-08-08 15:28 UTC, jwokaty commented on vignettes/contribute.Rmd
> +    install.packages("BiocManager")
Indent line 268.

2023-08-08 15:29 UTC, jwokaty commented on vignettes/contribute.Rmd
> +    BiocManager::install(Rnw2Rmd)
Rnw2Rmd is not yet part of Bioconductor. It's just in the Bioconductor GitHub. So you have to pass the owner/user part of the repo so that BiocManager knows it is a repository: `BiocManager::install("Bioconductor/Rnw2Rmd")`.

2023-08-08 15:52 UTC, jwokaty commented on vignettes/contribute.Rmd
> +    directly convert from Sweave (.Rnw) to R Markdown (.Rmd). `Rnw2Rmd` has some
I think we should change this section to

```
Note: Occasionally `Rnw2Rmd` has some`
```

because we used to do more intermediate steps before we made the .Rmd.

2023-08-08 15:53 UTC, jwokaty requested changes
Some small wording changes. Let's add the URL as you suggested to Rnw2Rmd. Thanks for updating the documentation.

2023-08-10 12:57 UTC, sonali8434 commented on vignettes/contribute.Rmd
> +* Rnw2Rmd
Can you please provide the relevant link attached here? I didn't find any.

2023-08-10 13:00 UTC, sonali8434 commented
@jwokaty I have made the requested changes; I didn't find any link online to be attached in Rnw2Rmd please help me find the right one.

2023-08-10 14:08 UTC, sonali8434 commented
@jwokaty Done with the link.

2023-08-10 14:08 UTC, sonali8434 commented on vignettes/contribute.Rmd
> +* Rnw2Rmd
Done

2023-08-15 02:18 UTC, jwokaty approved these changes

2023-08-15 02:20 UTC, merged